name: Manual Linux Release test

on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Person to greet'
        required: true
        default: 'Mona the Octocat'
      home:
        description: 'location'
        required: false
        default: 'The Octoverse'

defaults:
  run:
    shell: bash

env:
  SOURCE_DIR:   ${{ github.workspace }}
  QT_VERSION:   5.15.2
  ARTIFACT:     README.md

jobs:
  build:
    runs-on:  ubuntu-18.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          submodules: recursive
      

      - name: Nextcloud Artifact
        uses: trympet/nextcloud-artifacts-action@v2
        with:
          name: 'README.md'                                   # Name of the artifact
          path: 'README.md'                                  # Globbing supported
          nextcloud-url: 'https://cloud.hs-augsburg.de/'        # Nextcloud URL
          nextcloud-username: ${{ secrets.NEXTCLOUD_USERNAME }} # Username from repository secret
          nextcloud-password: ${{ secrets.NEXTCLOUD_PASSWORD }} # Password from repository secret
